Fix YAML formatting and indentation errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,21 +60,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      #step5 print pipeline summary
-      - name: print pipeline summary
+      - name: Print pipeline summary
         run: echo "Pipeline complete for commit: ${{ github.sha }}"
 
-      #steo 7 load and test secretly
       - name: Test secretly
         env:
           MY_SECRET: ${{ secrets.LAB_SECRET }}
         run: |
           if [ -n "$MY_SECRET" ]; then
-              echo "Secret loaded successfully"
-            else
-              echo "Secret is missing!"
-              exit 1
-            fi
-
-
-            
+            echo "Secret loaded successfully"
+          else
+            echo "Secret is missing!"
+            exit 1
+          fi
